---
# tasks file for suitecrm
- name: Download SuiteCRM
  get_url: 
    url=https://suitecrm.com/files/162/SuiteCRM-7.11/494/SuiteCRM-7.11.12.zip
    dest=/tmp/SuiteCRM-7.11.12.zip
    validate_certs=no


- name: Extract SuiteCRM
  unarchive: src=/tmp/SuiteCRM-7.11.12.zip dest=/var/www/html copy=no
  become: yes

- name: Change the dir
  command:  mv /var/www/html/SuiteCRM-7.11.12 /var/www/html/suitecrm
  become: yes

- name: Change the permission
  command:  chown -R www-data:www-data /var/www/html/suitecrm
  become: yes

- name: Change the permission
  command:  sudo chmod -R 755 /var/www/html/suitecrm
  become: yes


