---
# tasks file for server
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - apache2
    - apache2-utils
    - libapache2-mod-php
    - php7.2
    - php7.2-common
    - php7.2-curl
    - php7.2-xml
    - php7.2-json
    - php7.2-mysql
    - php7.2-mbstring
    - php7.2-zip
    - php7.2-imap
    - libpcre3
    - libpcre3-dev
    - zlib1g
    - zlib1g-dev
    - mariadb-server
    - unzip
    - python-mysqldb
